rotator:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  pan_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  tilt_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: tilt_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
